from classes.Functions import ask_directory, higher_resolution
import sys
import os
import shutil
import time


def get_yes_no(question=""):
    ans = input(question).lower()
    while ans not in ["y", "n"]:
        print("Please answer with 'y' or 'n'.")
        ans = input(question).lower()
    return ans


def insert_warning(file_path):
    with open(file_path, "r") as f:
        text = f.read()
    warning = "THIS IS A COPY OF PYGAME_ENGINE | DO NOT EDIT THIS FILE"
    l1 = "# ! " + len(warning)*"#" + " ! #"
    l2 = "# ! " + warning + " ! #"
    l3 = l1
    warning_text = "\n".join([l1, l2, l3])
    with open(file_path, "w") as f:
        f.write("\n" + warning_text + "\n"*2 + text)


if __name__ != "__main__":
    print("Run this file only by clicking on it or directly from the terminal\nand not within an editor!.")
    sys.exit()

higher_resolution()
print("This script creates a copy of the current state of Pygame_Engine.")
print("Do not run this script within an editor, as this might cause problems.")
input("To begin, press enter to choose the location where the folder should be created.\n")

run = True
while run:
    path = ask_directory()
    if path == "":
        print("Please choose a directory or close this application.")
        input("Press enter to continue.\n")
    else:
        print(path)
        print("Is this path correct? (y/n)")
        ans = get_yes_no()
        if ans == "y":
            run = False

main_new_path = os.path.join(path, "Pygame_Engine")
if os.path.exists(main_new_path):
    print("Pygame_Engine already exists at this location. Aborted process.")
    input("Press enter to exit.")
    sys.exit()
else:
    os.mkdir(main_new_path)

# specifying paths
from_classes_path = os.path.join(os.path.dirname(__file__), "classes")
from_images_path = os.path.join(os.path.dirname(__file__), "images")
from_init_file = os.path.join(os.path.dirname(__file__), "__init__.py")
to_classes_path = os.path.join(main_new_path, "classes")
to_images_path = os.path.join(main_new_path, "images")
to_init_file = os.path.join(main_new_path, "__init__.py")
info_file = os.path.join(main_new_path, "info.txt")

shutil.copytree(from_classes_path, to_classes_path)
shutil.copytree(from_images_path, to_images_path)
shutil.copyfile(from_init_file, to_init_file)

all_files = os.scandir(to_classes_path)
for f in all_files:
    if f.name.endswith(".py"):
        insert_warning(os.path.join(to_classes_path, f.name))

with open(os.path.join(main_new_path, "INFO.txt"), "w") as f:
    f.write(f"This folder is a copy of the Pygame_Engine library.\nDO NOT EDIT ANY FILE INSIDE THIS FOLDER!\n\nDate: {time.strftime('%d.%m.%Y, %H:%M:%S')}\nSrc folder:\t{os.path.dirname(__file__)}\nDst folder:\t{main_new_path}")

print("Successfully created copy of Pygame_Engine in desired directory.")
input("Press enter to exit.")